//! Per-domain instruction handlers + accounts. Each module here is its
//! own folder with a sibling `README.md` carrying a short audit memo
//! (authority discipline, CPI signers, invariants, risk surface). The
//! `lib.rs` `#[program]` block keeps thin wrappers that delegate to
//! these — the wrappers' bodies are one-liners, but their function
//! names (and therefore the Anchor ix discriminators) stay stable
//! across the move.
//!
//! * [`pool`] — pool lifecycle: init, register klend market, freeze /
//!   unfreeze, set elevation group / IRM curve / Civic gatekeeper,
//!   activate wrapping. See [`pool/README.md`](pool/README.md).
//! * [`admin`] — root authority + admin entries, whitelist plumbing
//!   (`add_participant*`, `add_wt_participant_via_pool`,
//!   `self_register`, `fix_co_authority`). See
//!   [`admin/README.md`](admin/README.md).
//! * [`wrap`] — plain wrap / unwrap / mint_wrapped (cUSDY-style 1:1
//!   custody). See [`wrap/README.md`](wrap/README.md).
//! * [`wrap_native`] — native-asset wrap / unwrap (cSOL, cUSDC; native
//!   pool seed shape). See
//!   [`wrap_native/README.md`](wrap_native/README.md).
//! * [`jito`] — Jito-vault wrap (`wrap_with_jito_vault`) plus the
//!   csSOL-WT lifecycle (`enqueue_withdraw_via_pool`,
//!   `mature_withdrawal_tickets`, `redeem_cssol_wt`) and queue helpers.
//!   See [`jito/README.md`](jito/README.md).
//! * [`solstice`] — Solstice eUSX → ceUSX-WT unlock + redeem, plus the
//!   bootstrap-only `admin_mint_wt`. See
//!   [`solstice/README.md`](solstice/README.md).

pub mod admin;
pub mod jito;
pub mod pool;
pub mod solstice;
pub mod wrap;
pub mod wrap_native;

// Re-export every public item (handlers, accounts structs, and the
// `__client_accounts_*` / `__cpi_client_accounts_*` helper modules
// generated by Anchor's `#[derive(Accounts)]` macro) so that the
// `#[program]` block at the crate root resolves account types and
// CPI clients via plain `crate::SomeAccountStruct` rather than long
// `crate::instructions::jito::SomeAccountStruct` paths. Anchor's
// generated dispatcher hard-codes `crate::` root lookups for these
// helpers, so flat re-exports are required for the program to compile.
pub use admin::*;
pub use jito::*;
pub use pool::*;
pub use solstice::*;
pub use wrap::*;
pub use wrap_native::*;
