import { PublicKey } from "@solana/web3.js";
export declare const DELTA_MINT_PROGRAM_ID: PublicKey;
export declare const GOVERNOR_PROGRAM_ID: PublicKey;
export declare const CLEARSTONE_CORE_PROGRAM_ID: PublicKey;
export declare const CLEARSTONE_ROUTER_PROGRAM_ID: PublicKey;
export declare const CLEARSTONE_CURATOR_PROGRAM_ID: PublicKey;
export declare const KAMINO_SY_ADAPTER_PROGRAM_ID: PublicKey;
export declare const GENERIC_EXCHANGE_RATE_SY_PROGRAM_ID: PublicKey;
export declare const KLEND_PROGRAM_ID: PublicKey;
export declare const TOKEN_2022_PROGRAM_ID: PublicKey;
export declare const TOKEN_PROGRAM_ID: PublicKey;
export declare const ASSOCIATED_TOKEN_PROGRAM_ID: PublicKey;
export declare const SYSTEM_PROGRAM_ID: PublicKey;
export declare const USDC_MINT: PublicKey;
export declare const USDY_MINT: PublicKey;
export declare const PYTH_USDY_PRICE: PublicKey;
export declare const PYTH_USDC_PRICE: PublicKey;
export declare const KLEND_GLOBAL_CONFIG: PublicKey;
export declare const DISC: {
    readonly initializeMint: Buffer<ArrayBuffer>;
    readonly addToWhitelist: Buffer<ArrayBuffer>;
    readonly mintTokens: Buffer<ArrayBuffer>;
    readonly initLendingMarket: Buffer<ArrayBuffer>;
    readonly initReserve: Buffer<ArrayBuffer>;
    readonly updateReserveConfig: Buffer<ArrayBuffer>;
    readonly initObligation: Buffer<ArrayBuffer>;
    readonly initUserMetadata: Buffer<ArrayBuffer>;
    readonly refreshReserve: Buffer<ArrayBuffer>;
    readonly depositReserveLiquidity: Buffer<ArrayBuffer>;
    readonly borrowObligationLiquidity: Buffer<ArrayBuffer>;
    readonly repayObligationLiquidity: Buffer<ArrayBuffer>;
    readonly withdrawObligationCollateral: Buffer<ArrayBuffer>;
};
export declare const CONFIG_MODE: {
    readonly UpdateLoanToValuePct: 0;
    readonly UpdateMaxLiquidationBonusBps: 1;
    readonly UpdateLiquidationThresholdPct: 2;
    readonly UpdateProtocolLiquidationFee: 3;
    readonly UpdateProtocolTakeRate: 4;
    readonly UpdateFeesBorrowFee: 5;
    readonly UpdateFeesFlashLoanFee: 6;
    readonly UpdateDepositLimit: 8;
    readonly UpdateBorrowLimit: 9;
    readonly UpdateTokenInfoLowerHeuristic: 10;
    readonly UpdateTokenInfoUpperHeuristic: 11;
    readonly UpdateTokenInfoExpHeuristic: 12;
    readonly UpdateTokenInfoTwapDivergence: 13;
    readonly UpdateTokenInfoName: 14;
    readonly UpdateScopePriceFeed: 15;
    readonly UpdateScopePriceChain: 16;
    readonly UpdateScopeTwapChain: 17;
    readonly UpdateTokenInfoMaxAgePriceSeconds: 18;
    readonly UpdateTokenInfoMaxAgeTwapSeconds: 19;
    readonly UpdatePythPrice: 20;
    readonly UpdateSwitchboardPrice: 21;
    readonly UpdateSwitchboardTwap: 22;
    readonly UpdateBorrowRateCurve: 23;
    readonly UpdateBorrowFactor: 25;
    readonly UpdateAssetTier: 28;
    readonly UpdateElevationGroup: 30;
    readonly UpdateMultiplierSideBoost: 32;
    readonly UpdateMultiplierTagBoost: 33;
    readonly UpdateReserveStatus: 34;
    readonly UpdateBadDebtLiquidationBonusBps: 39;
    readonly UpdateMinLiquidationBonusBps: 40;
    readonly UpdateAutodeleverageEnabled: 44;
    readonly UpdateDepositWithdrawalCap: 46;
    readonly UpdateDebtWithdrawalCap: 47;
    readonly UpdateUtilizationLimitBlockBorrowingAbove: 52;
    readonly UpdateBlockPriceUsage: 55;
};
